//console.log("quotes operational")

	//math.random generates a number in between 0 and 1
	//math.floor rounds the math.random
	//multiply by # of quotes
	
	var quoteArray = [
		['I know you&#39;re not supposed to cry over spilled tea,<br>But it&#39;s just so sad!', "Uncle Iroh"],
		['Sick of tea? That&#39;s like being sick of breathing!', "Uncle Iroh"],
		['Life happens wherever you are, whether you make it or not.', "Uncle Iroh"],
		['Prince Zuko, pride is not the opposite of shame, but it&#39;s source.<br>True humility is the only antidote to shame.', "Uncle Iroh"],
		['Sometimes life is like this dark tunnel,<br>You can&#39;t always see the light at the end of the tunnel,<Br>But if you just keep moving, you will come to a better place.', "Uncle Iroh"],
		['It&#39s important to draw wisdom from many different places...<br>If we take it from only one place it becomes rigid and stale.', "Uncle Iroh"],
		['Good times become good memories,<br>But bad times make good lessons.', "Uncle Iroh"],
		['Failure is only the opportunity to begin again.', "Uncle Iroh"],
		['In the darkest of times, hope is something you give yourself. <br> That is the meaning of inner strength', "Uncle Iroh"],
		['While it is always best to believe in oneself,<br>A little help from others can be a great blessing.', "Uncle Iroh"],
		['Sharing tea with a fascinating stranger is one of life&#39s true delights.', "Uncle Iroh"],
		['Destiny is a funny thing.<br>You never know how things are going to work out.<br>But if you keep an open mind and an open heart,<br>I promise you will find your own destiny someday.', "Uncle Iroh"],
		['SECRET TUNNELLLLLLLLLLLL<br>SECRET TUNNELLLLLLLLLLLL<br>THROUGH THE MOUNTAINS<br>Secret, Secret, Secret TUNNELLLL','Travelling Nomad, ATLA']
		['Where in the world is Carmen<br>Sandiego?','Unknown'],
		['The three chief virtues of a programmer are: Laziness, Impatience and Hubris.', 'Larry Wall',],
		['Persistence is very important. You should not give up unless you are forced to give up.', 'Elon Musk',],
		['I would like to die on Mars. Just not on impact.', 'Elon Musk',],
		['I can&#39;t change the direction of the wind, but I can adjust my sails to always reach my destination.', 'Jimmy Dean',],
		['It is during our darkest moments that we must focus to see the light.','Aristotle Onassis',],
		['Perfection is not attainable, but if we chase perfection we can catch excellence.', 'Vince Lombardi',],
		['We must let go of the life we have planned, so as to accept the one that is waiting for us.', 'Joseph Campbell',],
		['Don&#39;t judge each day by the harvest you reap but by the seeds that you plant.', 'Robert Louis Stevenson',],
		['{Insert Neha Quote}', 'Neha Kasoju',],
		['quote', 'Neha Kasoju',],
		['Keep your fears to yourself, but share your courage with others.', 'Robert Louis Stevenson',],
		['A person who never made a mistake never tried anything new.', 'Albert Einstein',],
		['I always wanted to be somebody, but now I realize I should have been more specific.', 'Lily Tomlin',],
		['Hello', 'Your FBI agent',],
		['Logic will get you from A to B. Imagination will take you everywhere.', 'Albert Einstein',],
		['There are no passengers on spaceship earth. We are all crew.', 'Marshall McLuhan',],
		['When we hit our lowest point, we are open to the greatest change.', 'Avatar Aang, Legend of Korra',],
		['Land on Mars, a round-trip ticket - half a million dollars. It can be done.','Elon Musk',],
		['The problem with being faster than light is that you can only live in darkness.','Meme, Unknown author',],
		['If you don&#39;t innovate, you will fall behind.'],
		['It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt.','Mark Twain',],
		['When all else is lost, the future still remains.','Christian Nestell Bovee',],
		['There are basically two types of people.<br>People who accomplish things, and people who claim to have accomplished things.<br>The first group is less crowded.','Mark Twain',],
		['I am a servant of the Secret Fire, wielder of the flame of Anwar.<br>YOU SHALL NOT PASS','Mo',],
		['You must do the things you think you cannot do.','Eleanor Roosevelt',],
		['Start by doing what&#39;s necessary, then do what&#39;s possible;<br>and suddenly you are doing the impossible.','Francis of Assisi',],
		['No act of kindness, no matter how small, is ever wasted.','Aesop'],
		['Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.','Rabindranath Tagore',],
		['What&#39;s another word for Thesaurus?','Steven Wright',],
		['I am not afraid of storms, For I am learning how to sail my ship.','Louisa May Alcott',],
		['The rich will do anything for the poor but get off their backs.','Karl Marx',],
		['It always seems impossible until it&#39;s done.','Nelson Mandela',],
		['Money printer go brrrrrrr.','Unknown Entity',],
		['You are now hacked','Hacker',],
		['I&#39;m not sure, I&#39;m getting back into the coding mindset though that&#39;s for sure.','Reese Chong'],
		['The more you have on your plate, the worse It&#39;be if you drop it.']
		['Politics can never be conquered, leave them to others.<br>You can win one election, rig the other ones.<br>But some day, your form of government will fall.','Mo'],
		['Quote printer go brrrr','Mo'],
		['The journey of a thousand miles begins with one step.','Lao Tzu'],
		['He is no fool who gives what he cannot keep to gain what he cannot lose.','Jim Elliot'],
		['Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.','Archimedes'],
		['Wherever there is a human being, there is an opportunity for a kindness.','Lucius Annaeus Seneca'],
		['Art is the triumph over chaos.','John Cheever'],
		['There is nothing in a caterpillar that tells you it&#39;s going to be a butterfly.','R. Buckminster Fuller'],
		['You can accomplish anything in life if you are willing to work for it.','Drew Brees'],
		['Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.','Buddha'],
		['He who has a why to live can bear almost any how.','Friedrich Nietzsche'],
		['We must be willing to let go of the life we have planned, so as to have the life that is waiting for us.','E. M. Forster'],
		['Not me','Neha'],
		['Why not do both?','Reese'],
		['Fluent, eh?<br>Me, I just dabble in languages.','Reese'],
		['Bingo','Bonk Meowlhead'],
		['BWAHAHAHA','Neha'],
		['If you get up in the morning and think the future is going to be better, it is a bright day.<br> Otherwise, it&#39;s not.','Elon Musk'],
		['Some people don&#39;t like change, but you need to embrace change if the alternative is disaster.','Elon Musk'],
		['If you do not have motivation<br>motivate a good friend<br>then watch, they will motivate you.','Mo'],
		['If your friend has never agreed with you, <br>never taken your side,<br>always used you, <br>ditch them, they are a bad friend.','Unknown'],
		['No u','Mo'],
		['If something&#39;s important enough, you should try.<br>-Even if - the probable outcome is failure.','Elon Musk'],
		['Don&#39;t write thirty quantitative sentences....<br>Only to get the same mark as the friend who wrote one qualitative sentence.','Mohammad A.'],
		['Patience is a virtue, and I&#39;m learning patience. It&#39;s a tough lesson.','Elon Musk'],
		['Any product that needs a manual to work is broken.','Elon Musk'],
		['Life is too short for long-term grudges.','Elon Musk'],
		['I think it matters whether someone has a good heart.','Elon Musk'],
		['If humanity doesn&#39;t land on Mars in my lifetime, I would be very disappointed.','Elon Musk'],
		['A real friend is one who walks in when the rest of the world walks out.','Walter Winchell'],
		['Never give in and never give up.','Hubert H. Humphrey'],
		['Life is 10% what happens to you and 90% how you react to it.','Charles R. Swindoll'],
		['Believe It!','Naruto'],
		['Those Who Break The Rules Are Scum<br>But, Those Who Abandon Their Friends Are Worse Than Scum.','Obito Uchiha'],
		['Someone who can&#39;t sacrifice anything, can&#39;t ever change anything.','Armin Arlert AOT'],
		['If you don&#39;t want to die...think','Levi Ackerman AOT'],
		['Endure it! Don&#39;t let go yet!-','Armin Arlert AOT'],
		['I&#39;m going to keep on making history.','Amanda Nunes'],
		['I&#39;m just going to have to keep working on what I have to and keep chasing my goals.','Grigor Dimitrov'],
		['I will always choose quality over quantity.','Amyra Dastur'],
		['Life is what happens while you are busy making other plans.','John Lennon'],
		['The only true wisdom is in knowing you know nothing.','Socrates'],
		['Every new beginning comes from some other beginning&#39;s end.','Seneca'],
		['Every day is a new day, and you&#39;ll never be able to find happiness if you don&#39;t move on.','Carrie Underwood'],
		['Don&#39;t write thirty quantitative paragraphs...<br>Only to get the same mark as the friend who wrote one qualitative paragraph.','Mohammad A.'],
		['Some cause happiness wherever they go; others whenever they go.','Oscar Wilde'],
		['It is during our darkest moments that we must focus to see the light.','Aristotle Onassis'],
		['We know what we are, but know not what we may be.','William Shakespeare'],
		['We need to innovate, become a multiplanetary species, and survive.','Mohammad A'],
		['When people complain I say: the U.G.C was not built in a day, it took years, hardcoding, programmers, geniuses, and a whole lot more!','Mohammad A.'],
		['Do not work hard, work smart!','Mohammad A.'],
		['Teamwork makes the dreams come true!','Mohammad A.'],
		['“Forty-two," said Deep Thought, with infinite majesty and calm.” “The Answer to the Great Question... Of Life, the Universe and Everything...:”','The Hitchhiker&#39;s Guide to the Galaxy'],
		['Pants are an illusion, and so is death.','Huu, ATLA'],	
		['The man who moves a mountain begins by carrying away small stones.','Confucius'],
		['The z&#39;s in this font look weird','zzz'],
		['Can you please type like a human and not like a monkey?','Neha'], 
		['An ounce of prevention is worth a pound of cure','Benjamin Franklin'],
		['A year from now, you may wish you had started today','Karen Lamb'],
		['Buh bye','Mo, 12:09 AM, 2021/01/27, UGCW'], 
		['woo poggers','Unknown author (Maybe Archimedes?)'],
		['Eh? Why make an ahen quote chat when we got UGCW. <br> UGCW is THE POG','Mo'],
		['To get the best people we try to make awesome offices','Unknown author'],
		['I spent two hours in shopify js, all I needed was 3 lines of CSS','Reese Chong'], 
		['If you know the enemy and know yourself, you need not fear the results of a hundred battles.','Sun Tzu'],
		['Know thyself','Socrates']
		['Never be afraid to sit a while and think.','Lorraine Hansberry'],
		['Knowledge is of no value unless you put it into practice.','Anton Chekhov'],
		['Being entirely honest with oneself is a good exercise.','Sigmund Freud'],
		['We cannot become what we need to be by remaining what we are.','Max de Pree'],
		['Set your course by the stars, not by the lights of every passing ship.','Omar N. Bradley'],
		['Be happy. It&#39;s one way of being wise.','Sidonie Gabrielle Colette'],
		['Today&#39;s mighty oak is just yesterday&#39;s nut, that held its ground.','David Icke'],
		['It&#39;s not what you look at that matters, it&#39;s what you see.','Henry David Thoreau'],
		['Slow and steady wins the race.','Robert Lloyd'],
		['You always have two choices: your commitment versus your fear.','Sammy Davis, Jr.'],
		['If the world were perfect, it wouldn&#39;t be.','Yogi Berra'],
		['Even if you&#39;re on the right track, you&#39;ll get run over if you just sit there.','Will Rogers'],
		['What happens is not as important as how you react to what happens.','Ellen Glasgow'],
		['In order to succeed, we must first believe that we can.','Nikos Kazantzakis'],
		['Expect problems and eat them for breakfast.','Alfred A. Montapert'],
		['Shoot for the moon. Even if you miss, you will land among the stars.','Norman Vincent Stone'],
		['Only I can change my life. No one can do it for me.','Carol Burnett'],
		['Quality is not an act, it is a habit.','Aristotle'],
		['Set your goals high, and don&#39;t stop till you get there.','Bo Jackson'],
		['Every exit is an entry somewhere else.','Tom Stoppard'],
		['I can, therefore I am.','Simone Weil'],
		['Leap, and the net will appear.','John Burroughs'],
		['Life is 10% what happens to you and 90% how you react to it.','Charles R. Swindoll'],
		['If you fell down yesterday, stand up today.','H. G. Wells'],
		['With the new day comes new strength and new thoughts.','Eleanor Roosevelt'],
		['Perseverance is not a long race; it is many short races one after the other.','Walter Elliot'],
		['Even if you fall on your face, you&#39;re still moving forward.','Victor Kiam'],
		['Never resign in chess, play honourably, you always have a chance to win','Mo'], 
		['Life is like chess, every move affects the next one, play wisely','Mo'],
		['Life is like chess, play wisely, and you can win','Mo'],
		['Trial by fire, a great way to learn','Unknown'],
		['If you can dream it, you can do it.','Walt Disney'],
		['Don&#39;t watch the clock; do what it does. Keep going.','Sam Levenson'],
		['Be kind whenever possible. It is always possible.','Dalai Lama'],
		['Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.','Samuel Beckett'],
		['When you reach the end of your rope, tie a knot in it and hang on.','Franklin D. Roosevelt'],
		['Problems are not stop signs, they are guidelines.','Robert H. Schuller'],
		['Either I will find a way, or I will make one.','Philip Sidney'],
		['No bird soars too high if he soars with his own wings.','William Blake'],
		['Without hard work, nothing grows but weeds.','Gordon B. Hinckley'],
		['I am not afraid... I was born to do this.','Joan of Arc'],
		['You just can&#39;t beat the person who never gives up.','Babe Ruth'],
		['Changes call for innovation, and innovation leads to progress.','Li Keqiang'],
		['There is no innovation and creativity without failure. Period.','Brene Brown'],
		['The heart and soul of the company is creativity and innovation.','Bob Iger'],
		['Innovation distinguishes between a leader and a follower.','Steve Jobs'],
		['Innovation is the calling card of the future.','Anna Eshoo'],
		['Innovation requires an experimental mindset.','Denise Morrison'],
		['Great companies are built on great products.','Elon Musk'],
		['Invest in Yourself and the Union!','U.G.C'],
		['Once you replace negative thoughts with positive ones, you&#39;ll start having positive results.','Willie Nelson'],
		['For the Union!','U.G.C'],
		['Yesterday is not ours to recover, but tomorrow is ours to win or lose.','Lyndon B. Johnson'],
		['A good laugh is sunshine in the house.','William Makepeace Thackeray'],
		['A strong, positive self-image is the best possible preparation for success.','Joyce Brothers'],
		['Live life to the fullest, and focus on the positive.','Matt Cameron'],
		['Always turn a negative situation into a positive situation.','Michael Jordan'],
		['Every day brings new choices.','Martha Beck'],
		['Work hard, stay positive, and get up early. It&#39;s the best part of the day.','George Allen, Sr.'],
		['Correction does much, but encouragement does more.','Johann Wolfgang von Goethe'],
		['All I want to do, ever, is play chess.','Bobby Fischer'],
		['In life, as in chess, forethought wins.','Charles Buxton'],
		['I like the feeling when you don&#39;t have much time and you have to think fast.','Hikaru Nakamura'],
		['Pride is not the opposite of shame, but its source.','Uncle Iroh'],
		['It&#39;s easy to do nothing, it&#39;s hard to forgive.','Aang'],
		['My cabbages!!','The Cabbage Merchant'],
		['You can&#39;t knock me down!','Katara'],
		['{Roar}','Appa'],
		['The past can be a great teacher','Aang'],
		['Anyone is capable of great good and great evil.','Aang'],
		['In the darkness, hope is something you give yourself','Uncle Iroh'],
		['There are reasons each of us are born. We have to find those reasons.','Uncle Iroh'],
		['I think you are very wise to choose happiness and love.','Uncle Iroh'],
		['Love is brightest in the dark.','Katara'],
		['I&#39;m too young to die!','Sokka'],
		['Don&#39;t you know that fans only make flames stronger?','Azula'],
		['There is no war in Ba Sing Se','Joo Dee (Not an Agent of the Dai Li)'],
		['You need to find someone who <u>waits</u> and <i>listens</i> before striking.','King Bumi'],
		['Squish, Squash, Sling that slang. I&#39;m always right back atcha, like my... <b>boomerang!','Sokka'],
		['A forgetful man walked into a bar...','I don&#39;t remember what he did next'],
		['Let go of your earthly tether. Enter the void, empty, and become wind','Guru Laghima'],
		['All roads lead to Rome','Latin proverb'],
		['Per aspera, ad astra','Seneca'],
		['I&#39;m the avatar, and you&#39;ve got to DEAL with it!','Korra'],
		['When we reach our lowest point, we are open to the greatest change.','Avatar Aang, LoK'],
		['You had a 1 in $x chance of seeing this quote.'.replace('$x', quoteNum),'UGCW Developers'],
	]
	
	var quoteNum = quoteArray.length
	
	var random_number = Math.floor(Math.random() * quoteNum);

	//console.log(quoteArray.length);
	document.getElementById("quotes").innerHTML = quoteArray[random_number][0];
	
	document.getElementById("author").innerHTML = "-" + quoteArray[random_number][1];
	
	//console.log(quoteArray[random_number][0])
	//console.log(quoteArray[random_number][1])
