//console.log("quotes operational")

	//math.random generates a number in between 0 and 1
	//math.floor rounds the math.random
	//multiply by # of quotes
	
	var quoteArray = [
		['I know you&#39;re not supposed to cry over spilled tea,<br>But it&#39;s just so sad!', "Uncle Iroh"],
		['Sick of tea? That&#39;s like being sick of breathing!', "Uncle Iroh"],
		['Life happens wherever you are, whether you make it or not.', "Uncle Iroh"],
		['Prince Zuko, pride is not the opposite of shame, but it&#39;s source.<br>True humility is the only antidote to shame.', "Uncle Iroh"],
		['Sometimes life is like this dark tunnel,<br>You can&#39;t always see the light at the end of the tunnel,<Br>But if you just keep moving, you will come to a better place.', "Uncle Iroh"],
		['It&#39s important to draw wisdom from many different places...<br>If we take it from only one place it becomes rigid and stale.', "Uncle Iroh"],
		['Good times become good memories,<br>But bad times make good lessons.', "Uncle Iroh"],
		['Failure is only the opportunity to begin again.', "Uncle Iroh"],
		['In the darkest of times, hope is something you give yourself. <br> That is the meaning of inner strength', "Uncle Iroh"],
		['While it is always best to believe in oneself,<br>A little help from others can be a great blessing.', "Uncle Iroh"],
		['Sharing tea with a fascinating stranger is one of life&#39s true delights.', "Uncle Iroh"],
		['Destiny is a funny thing.<br>You never know how things are going to work out.<br>But if you keep an open mind and an open heart,<br>I promise you will find your own destiny someday.', "Uncle Iroh"],
		['SECRET TUNNELLLLLLLLLLLL<br>SECRET TUNNELLLLLLLLLLLL<br>THROUGH THE MOUNTAINS<br>Secret, Secret, Secret TUNNELLLL','Travelling Nomad, ATLA']
		['Where in the world is Carmen<br>Sandiego?','Unknown'],
		['The three chief virtues of a programmer are: Laziness, Impatience and Hubris.', 'Larry Wall',],
		['Persistence is very important. You should not give up unless you are forced to give up.', 'Elon Musk',],
		['I would like to die on Mars. Just not on impact.', 'Elon Musk',],
		['I can&#39;t change the direction of the wind, but I can adjust my sails to always reach my destination.', 'Jimmy Dean',],
		['It is during our darkest moments that we must focus to see the light.','Aristotle Onassis',],
		['Perfection is not attainable, but if we chase perfection we can catch excellence.', 'Vince Lombardi',],
		['We must let go of the life we have planned, so as to accept the one that is waiting for us.', 'Joseph Campbell',],
		['Don&#39;t judge each day by the harvest you reap but by the seeds that you plant.', 'Robert Louis Stevenson',],
		['{Insert Neha Quote}', 'Neha Kasoju',],
		['quote', 'Neha Kasoju',],
		['Keep your fears to yourself, but share your courage with others.', 'Robert Louis Stevenson',],
		['A person who never made a mistake never tried anything new.', 'Albert Einstein',],
		['I always wanted to be somebody, but now I realize I should have been more specific.', 'Lily Tomlin',],
		['Hello', 'Your FBI agent',],
		['Logic will get you from A to B. Imagination will take you everywhere.', 'Albert Einstein',],
		['There are no passengers on spaceship earth. We are all crew.', 'Marshall McLuhan',],
		['When we hit our lowest point, we are open to the greatest change.', 'Avatar Aang, Legend of Korra',],
		['Land on Mars, a round-trip ticket - half a million dollars. It can be done.','Elon Musk',],
		['The problem with being faster than light is that you can only live in darkness.','Meme, Unknown author',],
		['If you don&#39;t innovate, you will fall behind.'],
		['It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt.','Mark Twain',],
		['When all else is lost, the future still remains.','Christian Nestell Bovee',],
		['There are basically two types of people.<br>People who accomplish things, and people who claim to have accomplished things.<br>The first group is less crowded.','Mark Twain',],
		['I am a servant of the Secret Fire, wielder of the flame of Anwar.<br>YOU SHALL NOT PASS','Mo',],
		['You must do the things you think you cannot do.','Eleanor Roosevelt',],
		['Start by doing what&#39;s necessary;<br>then do what&#39;s possible;<br>and suddenly you are doing the impossible.','Francis of Assisi',],
		['No act of kindness, no matter how small, is ever wasted.','Aesop'],
		['Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.','Rabindranath Tagore',],
		['What&#39;s another word for Thesaurus?','Steven Wright',],
		['I am not afraid of storms, For I am learning how to sail my ship.','Louisa May Alcott',],
		['The rich will do anything for the poor but get off their backs.','Karl Marx',],
		['It always seems impossible until it&#39;s done.','Nelson Mandela',],
		['Money printer go brrrrrrr.','Unknown Entity',],
		['You are now hacked','Hacker',],
		['I&#39;m not sure, I&#39;m getting back into the coding mindset though that&#39;s for sure.','Reese Chong'],
		['The more you have on your plate, the worse It&#39;be if you drop it.']
		['Politics can never be conquered, leave them to others.<br>You can win one election, rig the other ones.<br>But some day, your form of government will fall.','Mo'],
		['Quote printer go brrrr','Mo'],
		['The journey of a thousand miles begins with one step.','Lao Tzu'],
		['He is no fool who gives what he cannot keep to gain what he cannot lose.','Jim Elliot'],
		['Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.','Archimedes'],
		['Wherever there is a human being, there is an opportunity for a kindness.','Lucius Annaeus Seneca'],
		['Art is the triumph over chaos.','John Cheever'],
		['There is nothing in a caterpillar that tells you it&#39;s going to be a butterfly.','R. Buckminster Fuller'],
		['You can accomplish anything in life if you are willing to work for it.','Drew Brees'],
		['Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.','Buddha'],
		['He who has a why to live can bear almost any how.','Friedrich Nietzsche'],
		['We must be willing to let go of the life we have planned, so as to have the life that is waiting for us.','E. M. Forster'],
		['Not me','Neha'],
		['Why not do both?','Reese'],
		['Fluent, eh?<br>Me, I just dabble in languages.','Reese'],
		['Bingo','Bonk Meowlhead'],
		['BWAHAHAHA','Neha'],
		['If you get up in the morning and think the future is going to be better, it is a bright day.<br> Otherwise, it&#39;s not.','Elon Musk'],
		['Some people don&#39;t like change, but you need to embrace change if the alternative is disaster.','Elon Musk'],
		['If you do not have motivation<br>motivate a good friend<br>then watch, they will motivate you.','Mo'],
		['If your friend has never agreed with you, <br>never taken your side,<br>always used you, <br>ditch them, they are a bad friend.','Unknown'],
		['No u','Mo'],
		['There have to be reasons that you get up in the morning and you want to live.<br>Why do you want to live?What&#39;s the point? What inspires you?<br>What do you love about the future? If the future does not include being out there among the stars and being a multi-planet species, I find that incredibly depressing.','Elon Musk'],
		['If something&#39;s important enough, you should try.<br>-Even if - the probable outcome is failure.','Elon Musk'],
		['Don&#39;t write thirty quantitative sentences....<br>Only to get the same mark as the friend who wrote one qualitative sentence.','Mohammad A.'],
		['Patience is a virtue, and I&#39;m learning patience. It&#39;s a tough lesson.','Elon Musk'],
		['Any product that needs a manual to work is broken.','Elon Musk'],
		['Life is too short for long-term grudges.','Elon Musk'],
		['I think it matters whether someone has a good heart.','Elon Musk'],
		['If humanity doesn&#39;t land on Mars in my lifetime, I would be very disappointed.','Elon Musk'],
		['A real friend is one who walks in when the rest of the world walks out.','Walter Winchell'],
		['Never give in and never give up.','Hubert H. Humphrey'],
		['Life is 10% what happens to you and 90% how you react to it.','Charles R. Swindoll'],
		['Believe It!','Naruto'],
		['Those Who Break The Rules Are Scum<br>But, Those Who Abandon Their Friends Are Worse Than Scum.','Obito Uchiha'],
		['Someone who can&#39;t sacrifice anything, can&#39;t ever change anything.','Armin Arlert AOT'],
		['If you don&#39;t want to die...think','Levi Ackerman AOT'],
		['Endure it! Don&#39;t let go yet!-','Armin Arlert AOT'],
		['I&#39;m going to keep on making history.','Amanda Nunes'],
		['I&#39;m just going to have to keep working on what I have to and keep chasing my goals.','Grigor Dimitrov'],
		['I will always choose quality over quantity.','Amyra Dastur'],
		['Life is what happens while you are busy making other plans.','John Lennon'],
		['The only true wisdom is in knowing you know nothing.','Socrates'],
		['Every new beginning comes from some other beginning&#39;s end.','Seneca'],
		['Every day is a new day, and you&#39;ll never be able to find happiness if you don&#39;t move on.','Carrie Underwood'],
		['Don&#39;t write thirty quantitative paragraphs...<br>Only to get the same mark as the friend who wrote one qualitative paragraph.','Mohammad A.'],
		['Some cause happiness wherever they go; others whenever they go.','Oscar Wilde'],
		['It is during our darkest moments that we must focus to see the light.','Aristotle Onassis'],
		['We know what we are, but know not what we may be.','William Shakespeare'],
		['We need to innovate, become a multiplanetary species, and survive.','Mohammad A'],
		['When people complain I say: the U.G.C was not built in a day, it took years, hardcoding, programmers, geniuses, laziness and a whole lot more!','Mohammad A.'],
		['Do not work hard, work smart!','Mohammad A.'],
		['Teamwork makes the dreams come true!','Mohammad A.'],
		['“Forty-two," said Deep Thought, with infinite majesty and calm.” “The Answer to the Great Question... Of Life, the Universe and Everything...:”','The Hitchhiker&#39;s Guide to the Galaxy'],
		['Pants are an illusion, and so is death.','Huu, ATLA'],	
		['The man who moves a mountain begins by carrying away small stones.','Confucius'],
		['The z&#39;s in this font look weird','zzz'],
		['You had a 1 in $x chance of seeing this quote.'.replace('$x', quoteNum),'UGCW Developers'],
	]
	
	var quoteNum = quoteArray.length
	
	var random_number = Math.floor(Math.random() * quoteNum);

	//console.log(quoteArray.length);
	document.getElementById("quotes").innerHTML = quoteArray[random_number][0];
	
	document.getElementById("author").innerHTML = "-" + quoteArray[random_number][1];
	
	//console.log(quoteArray[random_number][0])
	//console.log(quoteArray[random_number][1])
